---

- hosts: k3s_cluster
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - { role: common, tags: ['common'] }    
    - { role: ssh, tags: ['ssh'] }    

- name: Build a cluster with a single control node
  hosts: k3s_cluster
  vars:
    k3s_become: true
  roles:
    - role: xanmanning.k3s
