---
- name: Configure sshd
  template:
    dest: /etc/ssh/sshd_config
    src: sshd_config
  notify:
    - Restart sshd

- name: Set ssh authorized_keys
  authorized_key:
    key: "{{ ssh_authorized_keys|join('\n') }}"
    user: root
    exclusive: false
